"use client";

import { FileUp, SearchCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export function ResumeAnalyzer() {
  const keywords = ["Redis", "CI/CD", "Observability", "PostgreSQL"];
  return (
    <section id="resume" className="space-y-4">
      <h2 className="text-xl font-semibold">AI resume analyzer</h2>
      <Card className="grid gap-5 lg:grid-cols-2">
        <div className="rounded-md border border-dashed border-border p-6">
          <FileUp className="h-8 w-8 text-primary" />
          <p className="mt-4 font-semibold">Upload PDF or DOCX</p>
          <p className="text-sm text-muted-foreground">Extract skills, projects, ATS score, and job-description alignment.</p>
          <Button className="mt-5">Choose resume</Button>
        </div>
        <div>
          <div className="flex items-center gap-3">
            <div className="grid h-20 w-20 place-items-center rounded-full border-8 border-primary text-xl font-bold">84</div>
            <div>
              <p className="font-semibold">ATS match score</p>
              <p className="text-sm text-muted-foreground">Missing keywords and improvements are generated by AI.</p>
            </div>
          </div>
          <div className="mt-5 grid grid-cols-2 gap-2">
            {keywords.map((keyword) => (
              <span className="inline-flex items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm" key={keyword}>
                <SearchCheck className="h-4 w-4 text-success" />
                {keyword}
              </span>
            ))}
          </div>
        </div>
      </Card>
    </section>
  );
}
