"use client";

import { ChangeEvent, useState } from "react";
import { FileUp, SearchCheck } from "lucide-react";
import { api } from "@/lib/api";
import { useSession } from "@/store/session";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

type ResumeAnalysis = {
  atsScore: number;
  matchedKeywords: string[];
  missingKeywords: string[];
  improvements: string[];
};

export function ResumeAnalyzer() {
  const accessToken = useSession((state) => state.accessToken);
  const [file, setFile] = useState<File>();
  const [jobDescription, setJobDescription] = useState("Full-stack TypeScript role with React, NestJS, PostgreSQL, CI/CD, and cloud deployment.");
  const [analysis, setAnalysis] = useState<ResumeAnalysis>();
  const [status, setStatus] = useState("Upload after sign-in to save resume analysis.");
  const [loading, setLoading] = useState(false);

  function onFileChange(event: ChangeEvent<HTMLInputElement>) {
    setFile(event.target.files?.[0]);
  }

  async function analyzeResume() {
    if (!accessToken) {
      setStatus("Sign in first to analyze a resume.");
      return;
    }
    if (!file) {
      setStatus("Choose a resume file first.");
      return;
    }
    const formData = new FormData();
    formData.set("resume", file);
    formData.set("jobDescription", jobDescription);
    setLoading(true);
    setStatus("Analyzing resume...");
    try {
      const result = await api<ResumeAnalysis>("/resume/analyze", {
        accessToken,
        method: "POST",
        body: formData
      });
      setAnalysis(result);
      setStatus("Resume analysis saved to backend.");
    } catch (error) {
      setStatus(error instanceof Error ? error.message : "Unable to analyze resume.");
    } finally {
      setLoading(false);
    }
  }

  const keywords = analysis?.matchedKeywords?.length ? analysis.matchedKeywords : ["Redis", "CI/CD", "Observability", "PostgreSQL"];

  return (
    <section id="resume" className="space-y-4">
      <h2 className="text-xl font-semibold">AI resume analyzer</h2>
      <Card className="grid gap-5 lg:grid-cols-2">
        <div className="rounded-md border border-dashed border-border p-6">
          <FileUp className="h-8 w-8 text-primary" />
          <p className="mt-4 font-semibold">Upload PDF, DOCX, or text resume</p>
          <p className="text-sm text-muted-foreground">Extract skills, projects, ATS score, and job-description alignment.</p>
          <input className="mt-5 block w-full text-sm" onChange={onFileChange} type="file" />
          <textarea
            className="mt-4 min-h-24 w-full rounded-md border border-border bg-background p-3 text-sm outline-none focus:ring-4 focus:ring-primary/30"
            onChange={(event) => setJobDescription(event.target.value)}
            value={jobDescription}
          />
          <Button className="mt-4" disabled={loading} onClick={analyzeResume}>
            {loading ? "Analyzing..." : "Analyze resume"}
          </Button>
          <p className="mt-3 text-xs text-muted-foreground">{status}</p>
        </div>
        <div>
          <div className="flex items-center gap-3">
            <div className="grid h-20 w-20 place-items-center rounded-full border-8 border-primary text-xl font-bold">{analysis?.atsScore ?? 84}</div>
            <div>
              <p className="font-semibold">ATS match score</p>
              <p className="text-sm text-muted-foreground">{analysis?.improvements?.[0] ?? "Missing keywords and improvements are generated by AI."}</p>
            </div>
          </div>
          <div className="mt-5 grid grid-cols-2 gap-2">
            {keywords.map((keyword) => (
              <span className="inline-flex items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm" key={keyword}>
                <SearchCheck className="h-4 w-4 text-success" />
                {keyword}
              </span>
            ))}
          </div>
          {!!analysis?.missingKeywords?.length && <p className="mt-4 text-sm text-muted-foreground">Missing: {analysis.missingKeywords.join(", ")}</p>}
        </div>
      </Card>
    </section>
  );
}
